### ISSUE TITLE
PHP8.3: Deprecation Notice from amphp/amp

### ISSUE THREAD

**Issue by jstoone** [spatie/php-structure-discoverer#12]
### Overview

When using php8.3 I encountered a deprecation warning originating from the wrap function in the functions.php file of the Amp package. The issue arises due an optional parameter being given before a required one: https://github.com/amphp/amp/blob/2.x/lib/functions.php#L573C46-L573C83

Which leads to the following being printed:
```
PHP Deprecated:  Optional parameter $exception declared before required parameter $result is implicitly treated as a required parameter in /Users/jstoone/Sites/good-tape/tape-vault/vendor/amphp/amp/lib/functions.php on line 556

Deprecated: Optional parameter $exception declared before required parameter $result is implicitly treated as a required parameter in /Users/jstoone/Sites/good-tape/tape-vault/vendor/amphp/amp/lib/functions.php on line 556
PHP Deprecated:  Optional parameter $exception declared before required parameter $result is implicitly treated as a required parameter in /Users/jstoone/Sites/good-tape/tape-vault/vendor/amphp/amp/lib/functions.php on line 556

Deprecated: Optional parameter $exception declared before required parameter $result is implicitly treated as a required parameter in /Users/jstoone/Sites/good-tape/tape-vault/vendor/amphp/amp/lib/functions.php on line 556
```

### Offer to contribute
First I thought to PR a change, but I noticed that this is for their `2.x`-branch, but instead I would be happy to contribute to the effort of upgrading to version 3 of `amphp/amp`.

### Additional information
But before I get into the nitty-gritty I'd like to hear your thoughts first. I tried running the test suite on 8.2, but I got the following stack trace:
<details>
  <summary>Failed to open stream: Too many open files</summary>
<pre><code>
(main) [137] % pest                                                                                                                                                         ~/Sites/github/php-structure-discoverer

   PASS  Tests\ReflectionTest
  ✓ it can reflect an interface
  ✓ it can reflect a class
  ✓ it can discover using reflection
  ✓ it can reflect an enum
  ✓ it can reflect a trait

   PASS  Tests\CacheDriversTest
  ✓ it can cache something with data set "laravel with store"
  ✓ it can cache something with data set "static"
  ✓ it can cache something with data set "file using php"
  ✓ it can cache something with data set "laravel"
  ✓ it can cache something with data set "laravel with prefix"
  ✓ it can cache something with data set "file with alternative filename"
  ✓ it can cache something with data set "file serialized"
PHP Warning:  include(/Users/jstoone/Sites/github/php-structure-discoverer/vendor/phpunit/phpunit/src/Framework/ExceptionWrapper.php): Failed to open stream: Too many open files in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576

Warning: include(/Users/jstoone/Sites/github/php-structure-discoverer/vendor/phpunit/phpunit/src/Framework/ExceptionWrapper.php): Failed to open stream: Too many open files in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576
PHP Warning:  include(): Failed opening '/Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/../phpunit/phpunit/src/Framework/ExceptionWrapper.php' for inclusion (include_path='.:/opt/homebrew/Cellar/php@8.2/8.2.14/share/php@8.2/pear') in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576

Warning: include(): Failed opening '/Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/../phpunit/phpunit/src/Framework/ExceptionWrapper.php' for inclusion (include_path='.:/opt/homebrew/Cellar/php@8.2/8.2.14/share/php@8.2/pear') in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576
Class "PHPUnit\Framework\ExceptionWrapper" not found
PHP Warning:  include(/Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/parallel/lib/Sync/ChannelledSocket.php): Failed to open stream: Too many open files in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576

Warning: include(/Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/parallel/lib/Sync/ChannelledSocket.php): Failed to open stream: Too many open files in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576
PHP Warning:  include(): Failed opening '/Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/../amphp/parallel/lib/Sync/ChannelledSocket.php' for inclusion (include_path='.:/opt/homebrew/Cellar/php@8.2/8.2.14/share/php@8.2/pear') in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576

Warning: include(): Failed opening '/Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/../amphp/parallel/lib/Sync/ChannelledSocket.php' for inclusion (include_path='.:/opt/homebrew/Cellar/php@8.2/8.2.14/share/php@8.2/pear') in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576
PHP Warning:  include(/Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/amp/lib/Failure.php): Failed to open stream: Too many open files in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576

Warning: include(/Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/amp/lib/Failure.php): Failed to open stream: Too many open files in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576
PHP Warning:  include(): Failed opening '/Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/../amphp/amp/lib/Failure.php' for inclusion (include_path='.:/opt/homebrew/Cellar/php@8.2/8.2.14/share/php@8.2/pear') in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576

Warning: include(): Failed opening '/Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/../amphp/amp/lib/Failure.php' for inclusion (include_path='.:/opt/homebrew/Cellar/php@8.2/8.2.14/share/php@8.2/pear') in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576
PHP Warning:  include(/Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/process/lib/ProcessException.php): Failed to open stream: Too many open files in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576

Warning: include(/Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/process/lib/ProcessException.php): Failed to open stream: Too many open files in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576
PHP Warning:  include(): Failed opening '/Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/../amphp/process/lib/ProcessException.php' for inclusion (include_path='.:/opt/homebrew/Cellar/php@8.2/8.2.14/share/php@8.2/pear') in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576

Warning: include(): Failed opening '/Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/../amphp/process/lib/ProcessException.php' for inclusion (include_path='.:/opt/homebrew/Cellar/php@8.2/8.2.14/share/php@8.2/pear') in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/composer/ClassLoader.php on line 576

Fatal error: Uncaught Error: Class "Amp\Process\ProcessException" not found in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/process/lib/Internal/Posix/Runner.php:202
Stack trace:
#0 /Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/process/lib/Process.php(141): Amp\Process\Internal\Posix\Runner->kill(Object(Amp\Process\Internal\Posix\Handle))
#1 /Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/parallel/lib/Context/Process.php(399): Amp\Process\Process->kill()
#2 /Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/parallel/lib/Worker/Internal/WorkerProcess.php(57): Amp\Parallel\Context\Process->kill()
#3 /Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/parallel/lib/Worker/TaskWorker.php(64): Amp\Parallel\Worker\Internal\WorkerProcess->kill()
#4 [internal function]: Amp\Parallel\Worker\TaskWorker::Amp\Parallel\Worker\{closure}()
#5 {main}
  thrown in /Users/jstoone/Sites/github/php-structure-discoverer/vendor/amphp/process/lib/Internal/Posix/Runner.php on line 202
[1]    65794 killed     pest
</code>
</pre>
</details>

**Comment by rubenvanassche** [comment]
You're always welcome to provide a PR upgrading to amp version 3, no idea why we've chosen 2.

**Comment by jstoone** [comment]
@rubenvanassche roger, thanks! I just wanted to check-in before I spent time on it.

**Comment by jameswagoner** [comment]
Well I started in on this issue too and didn't think I would have to side-track and learn Amphp.

@jstoone you get into the weeds after simply trying to bump dependency versions?

**Comment by jstoone** [comment]
Well done @jameswagoner !

To be honest, I got a bit overwhelmed by the endeavour, combined with workload. So, I got incredibly happy to see you PR! Thank you for this. ❤️ 🙏🏻
